### ISSUE TITLE
Build errors for v5.2

### ISSUE THREAD

**Issue by SimonDarksideJ** [Unity-UI-Extensions/com.unity.uiextensions#63]
<sup>Issue created by &lt;unknown&gt; as [Bitbucket Issue #&#8203;27](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/27) on 2015.09.28 17:53.</sup>
Hi,

When I build using on Unity 5.2.1 using 5.2 UI Ext, I get 21 errors. I'm using mono/net 4.0 to compile. The errors are all the same type of errors,  
e:\Unity Projects\Conq\Assets\unity-ui-extensions\Scripts\Accordion\Editor\AccordionElementEditor.cs(23,23): Error CS0246: The type or namespace name 'AccordionElement' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (Assembly-CSharp-Editor)

Rick

**Comment by SimonDarksideJ** [comment]
<sup>On [2015.09.28 18:18](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/27#comment-34323347), @SimonDarksideJ commented:</sup>
Are you using base 5.2.1 or 5.2.1p1?
I've seen reports that Unity have made yet more changes to the UI Mesh system which could have an impact but I've yet to verify.

I've tested the 5.2 package against a 5.2.1 base install and couldn't see any issues. (it's the version the latest videos were recorded on)

**Comment by SimonDarksideJ** [comment]
<sup>On [2015.09.29 18:49](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/27#comment-34323346), Rick Saul commented:</sup>
I'm using v5.2.1f1 Unity.

**Comment by SimonDarksideJ** [comment]
<sup>On [2015.10.05 11:49](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/27#comment-34323345), @SimonDarksideJ commented:</sup>
I've heard reports of errors in the patch releases, but the packages are all tested (and released) with the base releases of 4.6 / 5.1 and 5.2.1

**Comment by SimonDarksideJ** [comment]
<sup>On [2015.10.09 15:47](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/27#comment-34323344), @SimonDarksideJ commented:</sup>
Been reviewing the patch releases and the 5.3 beta and Unity have changed the method signatures for a lot of the UI functions.  This seems to have caught out a lot of asset / script developers.  
I'm going to create a 5.3 branch and update the scripts there, hopefully the 5.3 asset will be compatible with the 5.2.1+p  builds

**Comment by SimonDarksideJ** [comment]
<sup>On [2015.10.11 14:18](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/27#comment-34323343), @SimonDarksideJ commented:</sup>
Right sorted in this next release.  There will be a 5.3 build which can be uses in the 5.2.1Patch releases and higher.

**Comment by SimonDarksideJ** [comment]
<sup>On [2015.10.15 12:19](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/27#comment-34323342), @SimonDarksideJ commented:</sup>
New 5.3 branch / package published.
This can be used for 5.2.1P/5.3 builds

**Comment by SimonDarksideJ** [comment]
<sup>On 2015.10.15 12:19 @SimonDarksideJ modified issue:</sup>
**status** changed `new` → `resolved`
