### ISSUE TITLE
Does not compile in Unity 5.2.2p3

### ISSUE THREAD

**Issue by SimonDarksideJ** [Unity-UI-Extensions/com.unity.uiextensions#37]
<sup>Issue created by lostfictions as [Bitbucket Issue #&#8203;37](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/37) on 2015.11.09 06:51.</sup>
Using the 5.3 version of the package as suggested in the readme, Unity throws the following compile errors:

- Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(582,104): error CS1061: Type `UnityEngine.UI.InputField' does not contain a definition for `onValueChanged' and no extension method `onValueChanged' of type `UnityEngine.UI.InputField' could be found (are you missing a using directive or an assembly reference?)

- Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(582,36): error CS1502: The best overloaded method match for `UnityEditor.Events.UnityEventTools.AddPersistentListener<string>(UnityEngine.Events.UnityEvent<string>, UnityEngine.Events.UnityAction<string>)' has some invalid arguments

- Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(582,36): error CS1503: Argument `#1' cannot convert `object' expression to type `UnityEngine.Events.UnityEvent<string>'

- Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(678,104): error CS1061: Type `UnityEngine.UI.InputField' does not contain a definition for `onValueChanged' and no extension method `onValueChanged' of type `UnityEngine.UI.InputField' could be found (are you missing a using directive or an assembly reference?)

- Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(678,36): error CS1502: The best overloaded method match for `UnityEditor.Events.UnityEventTools.AddPersistentListener<string>(UnityEngine.Events.UnityEvent<string>, UnityEngine.Events.UnityAction<string>)' has some invalid arguments

- Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(678,36): error CS1503: Argument `#1' cannot convert `object' expression to type `UnityEngine.Events.UnityEvent<string>'
