### ISSUE TITLE
importing error

### ISSUE THREAD

**Issue by SimonDarksideJ** [Unity-UI-Extensions/com.unity.uiextensions#39]
<sup>Issue created by zitu as [Bitbucket Issue #&#8203;39](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/39) on 2015.11.23 11:59.</sup>
Hello! I just discovered this magnific project and downloaded it to try by myself.

Working with Unity 5.2.3f1, just downloaded your 5.3 package and when i try to import it, I get the following errors:

```comment

-----CompilerOutput:-stdout--exitcode: 1--compilationhadfailure: True--outfile: Temp/Assembly-CSharp-Editor.dll

Compilation failed: 6 error(s), 0 warnings

-----CompilerOutput:-stderr----------

Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(582,104): error CS1061: Type `UnityEngine.UI.InputField' does not contain a definition for `onValueChanged' and no extension method `onValueChanged' of type `UnityEngine.UI.InputField' could be found (are you missing a using directive or an assembly reference?)

Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(582,36): error CS1502: The best overloaded method match for `UnityEditor.Events.UnityEventTools.AddPersistentListener<string>(UnityEngine.Events.UnityEvent<string>, UnityEngine.Events.UnityAction<string>)' has some invalid arguments

C:\Program Files\UnityPersonal 5-2\Editor\Data\Managed\UnityEditor.dll (Location of the symbol related to previous error)

Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(582,36): error CS1503: Argument `#1' cannot convert `object' expression to type `UnityEngine.Events.UnityEvent<string>'

Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(678,104): error CS1061: Type `UnityEngine.UI.InputField' does not contain a definition for `onValueChanged' and no extension method `onValueChanged' of type `UnityEngine.UI.InputField' could be found (are you missing a using directive or an assembly reference?)

Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(678,36): error CS1502: The best overloaded method match for `UnityEditor.Events.UnityEventTools.AddPersistentListener<string>(UnityEngine.Events.UnityEvent<string>, UnityEngine.Events.UnityAction<string>)' has some invalid arguments

C:\Program Files\UnityPersonal 5-2\Editor\Data\Managed\UnityEditor.dll (Location of the symbol related to previous error)

Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(678,36): error CS1503: Argument `#1' cannot convert `object' expression to type `UnityEngine.Events.UnityEvent<string>'

-----EndCompilerOutput---------------

- Finished compile Library/ScriptAssemblies/Assembly-CSharp-Editor.dll
Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(582,104): error CS1061: Type `UnityEngine.UI.InputField' does not contain a definition for `onValueChanged' and no extension method `onValueChanged' of type `UnityEngine.UI.InputField' could be found (are you missing a using directive or an assembly reference?)
 
(Filename: Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs Line: 582)

Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(582,36): error CS1502: The best overloaded method match for `UnityEditor.Events.UnityEventTools.AddPersistentListener<string>(UnityEngine.Events.UnityEvent<string>, UnityEngine.Events.UnityAction<string>)' has some invalid arguments
 
(Filename: Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs Line: 582)

Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(582,36): error CS1503: Argument `#1' cannot convert `object' expression to type `UnityEngine.Events.UnityEvent<string>'
 
(Filename: Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs Line: 582)

Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(678,104): error CS1061: Type `UnityEngine.UI.InputField' does not contain a definition for `onValueChanged' and no extension method `onValueChanged' of type `UnityEngine.UI.InputField' could be found (are you missing a using directive or an assembly reference?)
 
(Filename: Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs Line: 678)

Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(678,36): error CS1502: The best overloaded method match for `UnityEditor.Events.UnityEventTools.AddPersistentListener<string>(UnityEngine.Events.UnityEvent<string>, UnityEngine.Events.UnityAction<string>)' has some invalid arguments
 
(Filename: Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs Line: 678)

Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(678,36): error CS1503: Argument `#1' cannot convert `object' expression to type `UnityEngine.Events.UnityEvent<string>'
 
(Filename: Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs Line: 678)
```
tried it in a newly created project. 

Would you know why is this happening? thanks a lot!

Zitu.
