### ISSUE TITLE
Does not compile in Unity 5.2.2p3

### ISSUE THREAD

**Issue by SimonDarksideJ** [Unity-UI-Extensions/com.unity.uiextensions#73]
<sup>Issue created by lostfictions as [Bitbucket Issue #&#8203;37](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/37) on 2015.11.09 06:51.</sup>
Using the 5.3 version of the package as suggested in the readme, Unity throws the following compile errors:

- Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(582,104): error CS1061: Type `UnityEngine.UI.InputField' does not contain a definition for `onValueChanged' and no extension method `onValueChanged' of type `UnityEngine.UI.InputField' could be found (are you missing a using directive or an assembly reference?)

- Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(582,36): error CS1502: The best overloaded method match for `UnityEditor.Events.UnityEventTools.AddPersistentListener<string>(UnityEngine.Events.UnityEvent<string>, UnityEngine.Events.UnityAction<string>)' has some invalid arguments

- Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(582,36): error CS1503: Argument `#1' cannot convert `object' expression to type `UnityEngine.Events.UnityEvent<string>'

- Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(678,104): error CS1061: Type `UnityEngine.UI.InputField' does not contain a definition for `onValueChanged' and no extension method `onValueChanged' of type `UnityEngine.UI.InputField' could be found (are you missing a using directive or an assembly reference?)

- Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(678,36): error CS1502: The best overloaded method match for `UnityEditor.Events.UnityEventTools.AddPersistentListener<string>(UnityEngine.Events.UnityEvent<string>, UnityEngine.Events.UnityAction<string>)' has some invalid arguments

- Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(678,36): error CS1503: Argument `#1' cannot convert `object' expression to type `UnityEngine.Events.UnityEvent<string>'

**Comment by SimonDarksideJ** [comment]
<sup>On [2015.11.09 16:21](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/37#comment-34323334), @SimonDarksideJ commented:</sup>
Oh dear lord, what has happened now.  Looks like they have deprecated the onValueChange event, or worse, renamed it.

It's fine in the current 5.3 beta, so need to wait for the next release to support this.

**Comment by SimonDarksideJ** [comment]
<sup>On [2015.11.19 01:23](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/37#comment-34323333), bugsy NA commented:</sup>
The current stable (5.2.2) docs make a very strong implication that they renamed it in 5.3 for consistency:
http://docs.unity3d.com/ScriptReference/30_search.html?q=onvaluechange  It's a bit annoying that this wasn't mentioned in the release notes.

It compiles fine without the 'd'.
However, this means that the 5.3 package is technically not 5.2.2-compatible.

**Comment by SimonDarksideJ** [comment]
<sup>On [2015.11.20 12:01](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/37#comment-34323332), @SimonDarksideJ commented:</sup>
Tested in the latest 5.2.3 build and found no issues.  Looks like it was just a blip in the patch release path.
Can you retest and confirm @lostfictions / @bugsy 

Also confirmed with the latest 5.3 RC that it also has no issues using the 5.3 build.

So just to confirm, for 5.2P+ / 5.2.3 and 5.3, you should use the 5.3 asset build.

**Comment by SimonDarksideJ** [comment]
<sup>On [2015.11.23 20:59](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/37#comment-34323331), @SimonDarksideJ commented:</sup>
See issue #39 for more details.

I've raised a bug report with Unity to explain what is going on.
In 4.6 -> 5.2 the event was called onValueChanged
in 5.2.xPx it was renamed to onValueChange
in 5.3 it's renamed back to onValueChanged

**Comment by SimonDarksideJ** [comment]
<sup>On [2015.11.23 21:00](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/37#comment-34323330), @SimonDarksideJ commented:</sup>
Oh and @bugsy it works still in 5.3 without the "d" because they left it in the API :S

**Comment by SimonDarksideJ** [comment]
<sup>On [2015.11.24 09:37](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/37#comment-34323329), @SimonDarksideJ commented:</sup>
Spent a good deal of time yesterday digging in to this and it looks like it was caused by a script upgrade with one of the recent 5.3 builds I've been using.
Going to patch it today and re-release the 5.3 asset with the old name.

**Comment by SimonDarksideJ** [comment]
<sup>On [2015.11.24 09:54](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/37#comment-34323328), @SimonDarksideJ commented:</sup>
Fixed. Please re-download asset, test and confirm and then close issue please.

**Comment by SimonDarksideJ** [comment]
<sup>On [2015.11.30 16:10](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/37#comment-34323327), @SimonDarksideJ commented:</sup>
Closing as duplicate issues noted it was resolved.

**Comment by SimonDarksideJ** [comment]
<sup>On 2015.11.30 16:10 @SimonDarksideJ modified issue:</sup>
**status** changed `new` → `resolved`
