### ISSUE TITLE
Script compiler errors on 1.0.6

### ISSUE THREAD

**Issue by SimonDarksideJ** [Unity-UI-Extensions/com.unity.uiextensions#43]
<sup>Issue created by Garret Polk as [Bitbucket Issue #&#8203;43](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/43) on 2015.12.05 00:41.</sup>
I got some script errors when upgrading from 1.0.5 to 1.0.6. I'm on Unity 5.2.3f1 and I used the 5.3 (5.2.1P+) asset. I managed to fix them, see below.

Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(582,104): error CS1061: Type `UnityEngine.UI.InputField' does not contain a definition for `onValueChanged' and no extension method `onValueChanged' of type `UnityEngine.UI.InputField' could be found (are you missing a using directive or an assembly reference?)

```c#

Events.UnityEventTools.AddPersistentListener<string>(inputField.GetComponent<InputField>().onValueChanged, new UnityEngine.Events.UnityAction<string>(autoCompleteComboBox.OnValueChanged));
```

I changed the part

```c#

GetComponent<InputField>().onValueChanged
```

to

```c#

GetComponent<InputField>().onValueChange
```
