### ISSUE TITLE
Build errors for v5.2

### ISSUE THREAD

**Issue by SimonDarksideJ** [Unity-UI-Extensions/com.unity.uiextensions#27]
<sup>Issue created by &lt;unknown&gt; as [Bitbucket Issue #&#8203;27](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/27) on 2015.09.28 17:53.</sup>
Hi,

When I build using on Unity 5.2.1 using 5.2 UI Ext, I get 21 errors. I'm using mono/net 4.0 to compile. The errors are all the same type of errors,  
e:\Unity Projects\Conq\Assets\unity-ui-extensions\Scripts\Accordion\Editor\AccordionElementEditor.cs(23,23): Error CS0246: The type or namespace name 'AccordionElement' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (Assembly-CSharp-Editor)

Rick
