### ISSUE TITLE
Does not  compile in Unity 2019.3.12f1

### ISSUE THREAD

**Issue by SimonDarksideJ** [Unity-UI-Extensions/com.unity.uiextensions#321]
<sup>Issue created by jedi as [Bitbucket Issue #&#8203;321](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/321) on 2020.05.06 00:53.</sup>
As soon as I’ve upgraded Unity to version 2019.3.12f1 the Visual Studio project started to give compilation errors, i.e.

Assets\\UIExtensions\\Editor\\CUIGraphicEditor.cs\(8,26,8,36\): error CS0246: The type or namespace name 'CUIGraphic' could not be found \(are you missing a using directive or an assembly reference?\)  
Assets\\UIExtensions\\Editor\\AccordionElementEditor.cs\(9,26,9,42\): error CS0246: The type or namespace name 'AccordionElement' could not be found \(are you missing a using directive or an assembly reference?\)  
Assets\\UIExtensions\\Editor\\UIExtensionsMenuOptions.cs\(348,80,348,90\): error CS0246: The type or namespace name 'ScrollSnap' could not be found \(are you missing a using directive or an assembly reference?\)  
Assets\\UIExtensions\\Editor\\CUIImageEditor.cs\(8,26,8,34\): error CS0246: The type or namespace name 'CUIImage' could not be found \(are you missing a using directive or an assembly reference?\)  
Assets\\UIExtensions\\Editor\\CUITextEditor.cs\(8,26,8,33\): error CS0246: The type or namespace name 'CUIText' could not be found \(are you missing a using directive or an assembly reference?\)  
Assets\\UIExtensions\\Editor\\ColorPickerPresetsEditor.cs\(6,23,6,41\): error CS0246: The type or namespace name 'ColorPickerPresets' could not be found \(are you missing a using directive or an assembly reference?\)  
Assets\\UIExtensions\\Editor\\FancyScrollView\\ScrollerEditor.cs\(11,26,11,34\): error CS0246: The type or namespace name 'Scroller' could not be found \(are you missing a using directive or an assembly reference?\)  
Assets\\UIExtensions\\Editor\\NonDrawingGraphicEditor.cs\(9,50,9,67\): error CS0246: The type or namespace name 'NonDrawingGraphic' could not be found \(are you missing a using directive or an assembly reference?\)  
Assets\\UIExtensions\\Editor\\RangeSliderEditor.cs\(11,26,11,37\): error CS0246: The type or namespace name 'RangeSlider' could not be found \(are you missing a using directive or an assembly reference?\)  
Assets\\UIExtensions\\Editor\\ReadOnlyDrawer.cs\(8,34,8,51\): error CS0246: The type or namespace name 'ReadOnlyAttribute' could not be found \(are you missing a using directive or an assembly reference?\)  
Assets\\UIExtensions\\Editor\\BezierLineRendererEditor.cs\(8,26,8,40\): error CS0246: The type or namespace name 'UILineRenderer' could not be found \(are you missing a using directive or an assembly reference?\)  
Assets\\UIExtensions\\Editor\\ScrollPositionControllerEditor.cs\(10,26,10,50\): error CS0246: The type or namespace name 'ScrollPositionController' could not be found \(are you missing a using directive or an assembly reference?\)  
Assets\\UIExtensions\\Editor\\BoxSliderEditor.cs\(9,26,9,35\): error CS0246: The type or namespace name 'BoxSlider' could not be found \(are you missing a using directive or an assembly reference?\)  
Assets\\UIExtensions\\Editor\\CUIBezierCurveEditor.cs\(8,26,8,40\): error CS0246: The type or namespace name 'CUIBezierCurve' could not be found \(are you missing a using directive or an assembly reference?\)  
Assets\\UIExtensions\\Editor\\TextPicEditor.cs\(9,26,9,33\): error CS0246: The type or namespace name 'TextPic' could not be found \(are you missing a using directive or an assembly reference?\)  
Assets\\UIExtensions\\Editor\\TextPicIconListCopier.cs\(43,16,43,23\): error CS0246: The type or namespace name 'TextPic' could not be found \(are you missing a using directive or an assembly reference?\)  
Assets\\UIExtensions\\Editor\\TextPicIconListCopier.cs\(78,11,78,18\): error CS0246: The type or namespace name 'TextPic' could not be found \(are you missing a using directive or an assembly reference?\)  

If I open my project in Unity 2019.3.11f1 everything is fine.
