### ISSUE TITLE
importing error

### ISSUE THREAD

**Issue by SimonDarksideJ** [Unity-UI-Extensions/com.unity.uiextensions#75]
<sup>Issue created by zitu as [Bitbucket Issue #&#8203;39](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/39) on 2015.11.23 11:59.</sup>
Hello! I just discovered this magnific project and downloaded it to try by myself.

Working with Unity 5.2.3f1, just downloaded your 5.3 package and when i try to import it, I get the following errors:

```comment

-----CompilerOutput:-stdout--exitcode: 1--compilationhadfailure: True--outfile: Temp/Assembly-CSharp-Editor.dll

Compilation failed: 6 error(s), 0 warnings

-----CompilerOutput:-stderr----------

Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(582,104): error CS1061: Type `UnityEngine.UI.InputField' does not contain a definition for `onValueChanged' and no extension method `onValueChanged' of type `UnityEngine.UI.InputField' could be found (are you missing a using directive or an assembly reference?)

Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(582,36): error CS1502: The best overloaded method match for `UnityEditor.Events.UnityEventTools.AddPersistentListener<string>(UnityEngine.Events.UnityEvent<string>, UnityEngine.Events.UnityAction<string>)' has some invalid arguments

C:\Program Files\UnityPersonal 5-2\Editor\Data\Managed\UnityEditor.dll (Location of the symbol related to previous error)

Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(582,36): error CS1503: Argument `#1' cannot convert `object' expression to type `UnityEngine.Events.UnityEvent<string>'

Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(678,104): error CS1061: Type `UnityEngine.UI.InputField' does not contain a definition for `onValueChanged' and no extension method `onValueChanged' of type `UnityEngine.UI.InputField' could be found (are you missing a using directive or an assembly reference?)

Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(678,36): error CS1502: The best overloaded method match for `UnityEditor.Events.UnityEventTools.AddPersistentListener<string>(UnityEngine.Events.UnityEvent<string>, UnityEngine.Events.UnityAction<string>)' has some invalid arguments

C:\Program Files\UnityPersonal 5-2\Editor\Data\Managed\UnityEditor.dll (Location of the symbol related to previous error)

Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(678,36): error CS1503: Argument `#1' cannot convert `object' expression to type `UnityEngine.Events.UnityEvent<string>'

-----EndCompilerOutput---------------

- Finished compile Library/ScriptAssemblies/Assembly-CSharp-Editor.dll
Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(582,104): error CS1061: Type `UnityEngine.UI.InputField' does not contain a definition for `onValueChanged' and no extension method `onValueChanged' of type `UnityEngine.UI.InputField' could be found (are you missing a using directive or an assembly reference?)
 
(Filename: Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs Line: 582)

Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(582,36): error CS1502: The best overloaded method match for `UnityEditor.Events.UnityEventTools.AddPersistentListener<string>(UnityEngine.Events.UnityEvent<string>, UnityEngine.Events.UnityAction<string>)' has some invalid arguments
 
(Filename: Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs Line: 582)

Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(582,36): error CS1503: Argument `#1' cannot convert `object' expression to type `UnityEngine.Events.UnityEvent<string>'
 
(Filename: Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs Line: 582)

Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(678,104): error CS1061: Type `UnityEngine.UI.InputField' does not contain a definition for `onValueChanged' and no extension method `onValueChanged' of type `UnityEngine.UI.InputField' could be found (are you missing a using directive or an assembly reference?)
 
(Filename: Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs Line: 678)

Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(678,36): error CS1502: The best overloaded method match for `UnityEditor.Events.UnityEventTools.AddPersistentListener<string>(UnityEngine.Events.UnityEvent<string>, UnityEngine.Events.UnityAction<string>)' has some invalid arguments
 
(Filename: Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs Line: 678)

Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs(678,36): error CS1503: Argument `#1' cannot convert `object' expression to type `UnityEngine.Events.UnityEvent<string>'
 
(Filename: Assets/unity-ui-extensions/Scripts/Editor/UIExtensionsMenuOptions.cs Line: 678)
```
tried it in a newly created project. 

Would you know why is this happening? thanks a lot!

Zitu.

**Comment by SimonDarksideJ** [comment]
<sup>On [2015.11.23 20:52](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/39#comment-34323391), @SimonDarksideJ commented:</sup>
It appears there has been a total muck up in the coding land, as indicated in the 5.3 RC
        //
        // Summary:
        //     Accessor to the OnChangeEvent.
        [Obsolete("onValueChange has been renamed to onValueChanged")]
So we have a bit of a quandry.  Unity changed the interface in one of the patch releases, realised they made a mistake but have decided NOT to fix it until 5.3??
Going to log a bug report

**Comment by SimonDarksideJ** [comment]
<sup>On [2015.11.24 08:47](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/39#comment-34323390), zitu commented:</sup>
Hi Simon!

Thanks for your fast answer. (after posting i saw that a related issue was opened some days ago :S ) Thanks also for reporting it to unity ;) perhaps as they are releasing unity 5.3 on December 8 ( if I'm not wrong) they decided not to publish a patch and just wait...  In the meantime I'll give a try to the "hard way" hehe.

**Comment by SimonDarksideJ** [comment]
<sup>On [2015.11.24 09:36](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/39#comment-34323389), @SimonDarksideJ commented:</sup>
Spent a good deal of time yesterday digging in to this and it looks like it was caused by a script upgrade with one of the recent 5.3 builds I've been using.
Going to patch it today and re-release the 5.3 asset with the old name.

**Comment by SimonDarksideJ** [comment]
<sup>On [2015.11.24 09:54](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/39#comment-34323388), @SimonDarksideJ commented:</sup>
Fixed. Please re-download asset, test and confirm and then close issue please.

**Comment by SimonDarksideJ** [comment]
<sup>On [2015.11.24 10:11](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/39#comment-34323387), zitu commented:</sup>
Hi again Simon!

redownloaded and working!;) thanks a lot and congrats for this great project!  

closing the issue

**Comment by SimonDarksideJ** [comment]
<sup>On [2015.11.24 10:12](https://bitbucket.org/UnityUIExtensions/unity-ui-extensions/issues/39#comment-34323386), zitu commented:</sup>
issue resolved

**Comment by SimonDarksideJ** [comment]
<sup>On 2015.11.24 10:12 zitu modified issue:</sup>
**status** changed `new` → `resolved`
