### ISSUE TITLE
BUG:  2022.2.3 errors and lockup

### ISSUE THREAD

**Issue by Ph0t0nX** [Unity-UI-Extensions/com.unity.uiextensions#421]
# Unity UI Extensions Bug Report

## Describe the bug
Does not work with 2022.2.3. It has compile errors and locks up.

## To Reproduce
1. Create an empty project (mine was URP 3D)
2. Project Settings/Player/Configuration/Active Input Handling: Input System Package (New)
3. Project Settings/Package Manager/Scoped Registries:
	Name: package.openupm.com
	URL: https://package.openupm.com
	Scopes: com.unity.uiextensions
4. Open Packages/manifest.json and add: "com.unity.uiextensions": "2.2.7",
5. See errors (Unity may lock up too)

## Expected behavior
No compiler errors and no lockups

## Actual behavior
There are three compiler errors.  Additionally, if you launch outside of safe-mode, the entire Unity window will become unresponsive permanently and must be killed via task-manager.  It will show a dialog saying "ProjectSettingsWindow.Repaint Waiting for Unity's code in UnityEditor.CoreModule.dll to finish executing".

## Screenshots
Library\PackageCache\com.unity.uiextensions@2.2.7\Runtime\Scripts\Utilities\UIExtensionsInputManager.cs(12,19): error CS0234: The type or namespace name 'InputSystem' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)

Library\PackageCache\com.unity.uiextensions@2.2.7\Runtime\Scripts\Utilities\UIExtensionsInputManager.cs(98,24): error CS0246: The type or namespace name 'ButtonControl' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.unity.uiextensions@2.2.7\Runtime\Scripts\Utilities\UIExtensionsInputManager.cs(177,24): error CS0246: The type or namespace name 'KeyControl' could not be found (are you missing a using directive or an assembly reference?)

## Your Setup

- **Operation System:**
    - [ X] Windows

- **Unity Version:** 2022.2.3f1
- **Unity UI Extensions Version**
    - [ 2.2.7 ] 

## Additional context
I don't know if there is a later version past 2.2.7. I tried putting 2.3.0 in the manifest and it said it can't be found. I also tried several variants of 2.5.0... 2.5.9 and nothing worked.  The wiki for explaining the Unity Package Manager install uses 2.2.4 and it does not explain how or where to find the latest version.

**Comment by Ph0t0nX** [comment]
This issue was resolved by adding "com.unity.uiextensions": "2.2.7", to the manifest.json file.

**Comment by SimonDarksideJ** [comment]
Thanks for the report, but I'll be sure to add 2022 (and 2023 for good measure) to the testing cycle for the 2.3 release
