### ISSUE TITLE
BUG: Unity 6.5 (6000.5.0f1) ExtensionMethods.cs and ColorPickerPresets.cs deprecation Error

### ISSUE THREAD

**Issue by GID0317** [Unity-UI-Extensions/com.unity.uiextensions#522]
After updating to the latest Unity 6.5, some components started showing errors and received deprecation warnings:

Assets\com.unity.uiextensions\Runtime\Scripts\Utilities\ExtensionMethods.cs(27,17): error CS0619: 'Object.GetInstanceID()' is obsolete: 'GetInstanceID is deprecated. Use GetEntityId instead. This will be removed in a future version.'

Assets\com.unity.uiextensions\Runtime\Scripts\Controls\ColorPicker\ColorPickerPresets.cs(38,38): error CS0619: 'Object.GetInstanceID()' is obsolete: 'GetInstanceID is deprecated. Use GetEntityId instead. This will be removed in a future version.'

**Comment by SimonDarksideJ** [comment]
In preparing the 3.0 release, I hit major issues with 6000.5 where Unity have been deprecating "Find" features and a bunch of other problems.
Will investigate once the release is out, and the initial version of the UIToolkitExtensions is launched

**Comment by XeonG** [comment]
UITOolkitExtensions .. whats in that?

**Comment by SimonDarksideJ** [comment]
> UIToolkitExtensions .. whats in that?

Like the UIExtensions is for uGui UI, the UIToolkit extensions is for Unity UI Toolkit UI
https://unity-ui-extensions.github.io/uitoolkit/
Still working on the release, lots to document but a good solid start with controls (similar to the uGUI package) and with better example scenes.

**Comment by XeonG** [comment]
any update on making ugui extensions work on 6.6+  needed more than uitoolkit stuff as none of my projects can be tested on newer release including 6.7 coreclr builds 

though interesting, uitoolkit absolutely needs more richer components to use, the ui toolkit appui package has many aswel but also no support and bugs, would be good to see alot of that in a supported ui extension

**Comment by SimonDarksideJ** [comment]
Sadly got drawn away by contracts, but will see what can be done, easy to test by expanding the unit testing. 

Uitoolkit controls are ready, as documented on the website, but it's in the review phase which just takes time sadly.

**Comment by SimonDarksideJ** [comment]
OK, test run setup for Unity 5-7, now need to work through the issues
https://github.com/Unity-UI-Extensions/com.unity.uiextensions/actions/runs/29191133571/job/86645883246

**Comment by XeonG** [comment]
doesn't look like its showing the actual code errors yet just the build target Build failed for target: StandaloneWindows64 (exit code: 1)

**Comment by SimonDarksideJ** [comment]
Oh they are there, the actions view just hides them with Unity builds, because Unity....

```text
##### Output
  Packages\UPM\Runtime\Scripts\Controls\ColorPicker\ColorPickerPresets.cs(38,38): error CS0619: 'Object.GetInstanceID()' is obsolete: 'GetInstanceID is deprecated. Use GetEntityId instead. This will be removed in a future version.'
  
  Packages\UPM\Runtime\Scripts\Controls\ReorderableList\ReorderableListDebug.cs(13,69): warning CS0618: 'FindObjectsSortMode' is obsolete: 'FindObjectsSortMode has been deprecated. Use the FindObjectsByType overloads that do not take a FindObjectsSortMode parameter.'
  
  Packages\UPM\Runtime\Scripts\Controls\ReorderableList\ReorderableListDebug.cs(13,34): warning CS0618: 'Object.FindObjectsByType<T>(FindObjectsSortMode)' is obsolete: 'FindObjectsByType with FindObjectsSortMode parameter has been deprecated. Use FindObjectsByType<T>() or FindObjectsByType<T>(FindObjectsInactive) instead. InstanceID will be replaced in the future with EntityId and previous sort order cannot be maintained.'
  
  Packages\UPM\Runtime\Scripts\Controls\SelectionBox\SelectionBox.cs(184,81): warning CS0618: 'FindObjectsSortMode' is obsolete: 'FindObjectsSortMode has been deprecated. Use the FindObjectsByType overloads that do not take a FindObjectsSortMode parameter.'
  
  Packages\UPM\Runtime\Scripts\Controls\SelectionBox\SelectionBox.cs(184,37): warning CS0618: 'Object.FindObjectsByType<T>(FindObjectsSortMode)' is obsolete: 'FindObjectsByType with FindObjectsSortMode parameter has been deprecated. Use FindObjectsByType<T>() or FindObjectsByType<T>(FindObjectsInactive) instead. InstanceID will be replaced in the future with EntityId and previous sort order cannot be maintained.'
  
  Packages\UPM\Runtime\Scripts\Utilities\ExtensionMethods.cs(27,17): error CS0619: 'Object.GetInstanceID()' is obsolete: 'GetInstanceID is deprecated. Use GetEntityId instead. This will be removed in a future version.'
  
  Packages\UPM\Runtime\Scripts\ToolTips\ToolTip.cs(94,32): warning CS0618: 'Object.FindFirstObjectByType<T>()' is obsolete: 'FindFirstObjectByType has been deprecated because it relies on instance ID ordering. Use FindAnyObjectByType instead, which does not depend on ordering.'
  
  Packages\UPM\Runtime\Scripts\ToolTips\BoundTooltip\BoundTooltipItem.cs(50,32): warning CS0618: 'Object.FindFirstObjectByType<T>()' is obsolete: 'FindFirstObjectByType has been deprecated because it relies on instance ID ordering. Use FindAnyObjectByType instead, which does not depend on ordering.'
  
  Packages\UPM\Runtime\Scripts\Controls\ColorPicker\ColorPickerControl.cs(21,26): warning UAC1001: Field 'onHSVChanged' type 'UnityEngine.UI.Extensions.ColorPicker.HSVChangedEvent' is skipped by serialization (missing the [Serializable] attribute). Refer to the Serialization rules analyzer reference. (https://docs.unity3d.com/6000.5/Documentation/Manual/script-serialization-analyzer.html#uac1001)
  
  Packages\UPM\Runtime\Scripts\Controls\SelectionBox\SelectionBox.cs(70,25): warning UAC1001: Field 'onSelectionChange' type 'UnityEngine.UI.Extensions.SelectionBox.SelectionEvent' is skipped by serialization (missing the [Serializable] attribute). Refer to the Serialization rules analyzer reference. (https://docs.unity3d.com/6000.5/Documentation/Manual/script-serialization-analyzer.html#uac1001)
  *** Tundra build failed (6.63 seconds), 19 items updated, 939 evaluated
  ## Script Compilation Error for: Csc Library/Bee/artifacts/1900b0aE.dag/UnityUIExtensions.dll (+2 others)
  ## CmdLine: "C:\Program Files\Unity\Hub\Editor\6000.5.3f1\Editor\Data\DotNetSdk\dotnet.exe" exec "C:/Program Files/Unity/Hub/Editor/6000.5.3f1/Editor/Data/DotNetSdk/sdk/8.0.318/Roslyn/bincore/csc.dll" /nostdlib /noconfig /shared "@Library/Bee/artifacts/1900b0aE.dag/UnityUIExtensions.rsp" "@Library/Bee/artifacts/1900b0aE.dag/UnityUIExtensions.rsp2"
  ## Output:
  Packages\UPM\Runtime\Scripts\Controls\ColorPicker\ColorPickerPresets.cs(38,38): error CS0619: 'Object.GetInstanceID()' is obsolete: 'GetInstanceID is deprecated. Use GetEntityId instead. This will be removed in a future version.'
  Packages\UPM\Runtime\Scripts\Controls\ReorderableList\ReorderableListDebug.cs(13,69): warning CS0618: 'FindObjectsSortMode' is obsolete: 'FindObjectsSortMode has been deprecated. Use the FindObjectsByType overloads that do not take a FindObjectsSortMode parameter.'
  Packages\UPM\Runtime\Scripts\Controls\ReorderableList\ReorderableListDebug.cs(13,34): warning CS0618: 'Object.FindObjectsByType<T>(FindObjectsSortMode)' is obsolete: 'FindObjectsByType with FindObjectsSortMode parameter has been deprecated. Use FindObjectsByType<T>() or FindObjectsByType<T>(FindObjectsInactive) instead. InstanceID will be replaced in the future with EntityId and previous sort order cannot be maintained.'
  Packages\UPM\Runtime\Scripts\Controls\SelectionBox\SelectionBox.cs(184,81): warning CS0618: 'FindObjectsSortMode' is obsolete: 'FindObjectsSortMode has been deprecated. Use the FindObjectsByType overloads that do not take a FindObjectsSortMode parameter.'
  Packages\UPM\Runtime\Scripts\Controls\SelectionBox\SelectionBox.cs(184,37): warning CS0618: 'Object.FindObjectsByType<T>(FindObjectsSortMode)' is obsolete: 'FindObjectsByType with FindObjectsSortMode parameter has been deprecated. Use FindObjectsByType<T>() or FindObjectsByType<T>(FindObjectsInactive) instead. InstanceID will be replaced in the future with EntityId and previous sort order cannot be maintained.'
  Packages\UPM\Runtime\Scripts\Utilities\ExtensionMethods.cs(27,17): error CS0619: 'Object.GetInstanceID()' is obsolete: 'GetInstanceID is deprecated. Use GetEntityId instead. This will be removed in a future version.'
  Packages\UPM\Runtime\Scripts\ToolTips\ToolTip.cs(94,32): warning CS0618: 'Object.FindFirstObjectByType<T>()' is obsolete: 'FindFirstObjectByType has been deprecated because it relies on instance ID ordering. Use FindAnyObjectByType instead, which does not depend on ordering.'
  Packages\UPM\Runtime\Scripts\ToolTips\BoundTooltip\BoundTooltipItem.cs(50,32): warning CS0618: 'Object.FindFirstObjectByType<T>()' is obsolete: 'FindFirstObjectByType has been deprecated because it relies on instance ID ordering. Use FindAnyObjectByType instead, which does not depend on ordering.'
  Packages\UPM\Runtime\Scripts\Controls\ColorPicker\ColorPickerControl.cs(21,26): warning UAC1001: Field 'onHSVChanged' type 'UnityEngine.UI.Extensions.ColorPicker.HSVChangedEvent' is skipped by serialization (missing the [Serializable] attribute). Refer to the Serialization rules analyzer reference. (https://docs.unity3d.com/6000.5/Documentation/Manual/script-serialization-analyzer.html#uac1001)
  Packages\UPM\Runtime\Scripts\Controls\SelectionBox\SelectionBox.cs(70,25): warning UAC1001: Field 'onSelectionChange' type 'UnityEngine.UI.Extensions.SelectionBox.SelectionEvent' is skipped by serialization (missing the [Serializable] attribute). Refer to the Serialization rules analyzer reference. (https://docs.unity3d.com/6000.5/Documentation/Manual/script-serialization-analyzer.html#uac1001)
  
  Packages\UPM\Runtime\Scripts\Controls\ColorPicker\ColorPickerPresets.cs(38,38): error CS0619: 'Object.GetInstanceID()' is obsolete: 'GetInstanceID is deprecated. Use GetEntityId instead. This will be removed in a future version.'
  Packages\UPM\Runtime\Scripts\Controls\ReorderableList\ReorderableListDebug.cs(13,69): warning CS0618: 'FindObjectsSortMode' is obsolete: 'FindObjectsSortMode has been deprecated. Use the FindObjectsByType overloads that do not take a FindObjectsSortMode parameter.'
  Packages\UPM\Runtime\Scripts\Controls\ReorderableList\ReorderableListDebug.cs(13,34): warning CS0618: 'Object.FindObjectsByType<T>(FindObjectsSortMode)' is obsolete: 'FindObjectsByType with FindObjectsSortMode parameter has been deprecated. Use FindObjectsByType<T>() or FindObjectsByType<T>(FindObjectsInactive) instead. InstanceID will be replaced in the future with EntityId and previous sort order cannot be maintained.'
  Packages\UPM\Runtime\Scripts\Controls\SelectionBox\SelectionBox.cs(184,81): warning CS0618: 'FindObjectsSortMode' is obsolete: 'FindObjectsSortMode has been deprecated. Use the FindObjectsByType overloads that do not take a FindObjectsSortMode parameter.'
  Packages\UPM\Runtime\Scripts\Controls\SelectionBox\SelectionBox.cs(184,37): warning CS0618: 'Object.FindObjectsByType<T>(FindObjectsSortMode)' is obsolete: 'FindObjectsByType with FindObjectsSortMode parameter has been deprecated. Use FindObjectsByType<T>() or FindObjectsByType<T>(FindObjectsInactive) instead. InstanceID will be replaced in the future with EntityId and previous sort order cannot be maintained.'
  Packages\UPM\Runtime\Scripts\Utilities\ExtensionMethods.cs(27,17): error CS0619: 'Object.GetInstanceID()' is obsolete: 'GetInstanceID is deprecated. Use GetEntityId instead. This will be removed in a future version.'
  Packages\UPM\Runtime\Scripts\ToolTips\ToolTip.cs(94,32): warning CS0618: 'Object.FindFirstObjectByType<T>()' is obsolete: 'FindFirstObjectByType has been deprecated because it relies on instance ID ordering. Use FindAnyObjectByType instead, which does not depend on ordering.'
  Packages\UPM\Runtime\Scripts\ToolTips\BoundTooltip\BoundTooltipItem.cs(50,32): warning CS0618: 'Object.FindFirstObjectByType<T>()' is obsolete: 'FindFirstObjectByType has been deprecated because it relies on instance ID ordering. Use FindAnyObjectByType instead, which does not depend on ordering.'
  Packages\UPM\Runtime\Scripts\Controls\ColorPicker\ColorPickerControl.cs(21,26): warning UAC1001: Field 'onHSVChanged' type 'UnityEngine.UI.Extensions.ColorPicker.HSVChangedEvent' is skipped by serialization (missing the [Serializable] attribute). Refer to the Serialization rules analyzer reference. (https://docs.unity3d.com/6000.5/Documentation/Manual/script-serialization-analyzer.html#uac1001)
  Packages\UPM\Runtime\Scripts\Controls\SelectionBox\SelectionBox.cs(70,25): warning UAC1001: Field 'onSelectionChange' type 'UnityEngine.UI.Extensions.SelectionBox.SelectionEvent' is skipped by serialization (missing the [Serializable] attribute). Refer to the Serialization rules analyzer reference. (https://docs.unity3d.com/6000.5/Documentation/Manual/script-serialization-analyzer.html#uac1001)
```

**Comment by XeonG** [comment]
oh the instanceId ones are the fairly easy fixes.. I had tried fixing it myself, but I think its hiding alot more after those are fixed as they did something with Layout stuff in 6.6 and that didn't seem easy to fix as no idea how that was working in the first place .  ie this stuff https://github.com/Unity-UI-Extensions/com.unity.uiextensions/issues/520

**Comment by SimonDarksideJ** [comment]
NWS, it is a priority and I will get to this asap, sorry for your troubles.

**Comment by SimonDarksideJ** [comment]
Fun fun fun, fixed all the 6.4 issues, now more issues are appearing in even later versions. Fantastic Unity,,, again

**Comment by XeonG** [comment]
I dunno why you didn't just go straight to fixing them on 6.7a which is out now, it is the next LTS afteral, nobody bothers with the interim versions they last about 3months before even unity doesn't bother supporting them

**Comment by SimonDarksideJ** [comment]
OK, Unity 6000.6/7 patched, new run progressing :D

https://github.com/Unity-UI-Extensions/com.unity.uiextensions/actions/runs/29749332547

**Comment by XeonG** [comment]
yeah it was these ones SetLayoutInputForAxis(minWidth, -1, -1, 0, 0); that I wasn't sure about how to fix.. good to see it might all work on 6.7 now though

**Comment by SimonDarksideJ** [comment]
> yeah it was these ones SetLayoutInputForAxis(minWidth, -1, -1, 0, 0); that I wasn't sure about how to fix.. good to see it might all work on 6.7 now though

Everything tested and working under 6.7 now.  Will do some more checks on that PR and update the development branch for use.

**Comment by SimonDarksideJ** [comment]
> I dunno why you didn't just go straight to fixing them on 6.7a 

Because Unity...  Experience has taught me over the decades to tread lightly with Unity and just because you fix something in the later release does not mean it will continue to work with earlier versions.

As an Asst author, I have to ensure that the package works, no matter who uses it :D

**Comment by SimonDarksideJ** [comment]
Merged to development, if you want to test @GID0317
